"""Head-to-head benchmark harness — honestly measure bad-research against a
commercial Deep Research tool (Gemini / OpenAI / Perplexity / Grok DR) on a
shared query set, scored by the EXISTING categorical (E2) judge.

Honesty boundary (this is the apparatus, NOT a claimed win):
  - Competitor RUNS are MANUAL. No product is called from here; a human pastes
    the competitor's report as a file. This module never proves a win — it makes
    a win (or a loss) measurable and reproducible.
  - Scoring reuses `calibrate.judge` verbatim: the keyless deterministic
    `RubricJudge` by default ($0, offline), or the host-model `LLMJudge` on the
    opt-in `--llm` path. The RubricJudge's documented scope limits (golden.py:130)
    apply here too: it is a grounding-overlap + citation-presence proxy, NOT
    semantic entailment. Read the scorecard's `disclaimer` before quoting it.
  - BLINDING: every entrant report is stripped of tool-identifying markers before
    it reaches the judge, so the categorical verdict cannot be biased by which
    tool produced the text. Blinding is lexical and best-effort — it removes the
    markers we know about; see `TOOL_MARKERS`.

The protocol that frames this lives in `docs/benchmarks/HEAD_TO_HEAD.md`; the
shared starter query set in `docs/benchmarks/queries/starter_set.json`.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from bad_research.calibrate.constants import JUDGE_AXES, RAIL_CREDIT
from bad_research.calibrate.golden import RubricJudge
from bad_research.calibrate.judge import (
    JUDGE_SYSTEM,
    AxisRails,
    HostJudge,
    Judge,
    JudgeVerdict,
    build_judge_user_prompt,
)

# ── blinding: known tool-identifying markers ────────────────────────────────────
# Lexical substrings (case-insensitive) that name or fingerprint a producing tool.
# Stripped from every entrant report BEFORE judging so the categorical verdict is
# tool-agnostic. Best-effort: removes the markers we know about, not a guarantee.
TOOL_MARKERS: tuple[str, ...] = (
    # bad-research family
    "bad-research",
    "bad research",
    "badresearch",
    "hyperresearch",
    "michael jackson bad",
    # commercial Deep Research tools
    "gemini deep research",
    "gemini advanced",
    "gemini",
    "openai deep research",
    "chatgpt deep research",
    "chatgpt",
    "openai",
    "gpt-4",
    "gpt-5",
    "perplexity pro",
    "perplexity",
    "grok deepsearch",
    "grok",
    "claude",
    "anthropic",
    "google deepmind",
    "deepmind",
)

# A redaction token the judge sees in place of a stripped marker. Neutral; carries
# no tool identity. Collapsed whitespace keeps the redacted text readable.
_REDACTED = "[tool]"


def blind_report(report: str, *, extra_markers: tuple[str, ...] = ()) -> str:
    """Strip known tool-identifying markers from `report` so the judge cannot be
    biased by which tool produced it. Case-insensitive whole-substring replace;
    longest markers first so e.g. 'gemini deep research' is removed before 'gemini'.
    Also strips a leading 'Produced by ...'/'Generated by ...' attribution line and
    common bad-research scaffold frontmatter keys. Deterministic and offline."""
    markers = sorted(set(TOOL_MARKERS) | set(extra_markers), key=len, reverse=True)
    out = report
    for m in markers:
        if not m:
            continue
        out = re.sub(re.escape(m), _REDACTED, out, flags=re.IGNORECASE)
    # Strip an attribution line like "Produced by X" / "Generated by X" / "Source: X".
    out = re.sub(
        r"(?im)^\s*(produced|generated|written|created|powered)\s+by\b.*$",
        "",
        out,
    )
    out = re.sub(r"(?im)^\s*(source|tool|model|system)\s*:\s*.*$", "", out)
    return out


def markers_present(report: str, *, extra_markers: tuple[str, ...] = ()) -> list[str]:
    """The known tool markers that appear in `report` (case-insensitive). Empty list
    iff the report is already blind. Useful for asserting blinding worked."""
    rl = report.lower()
    return [m for m in (set(TOOL_MARKERS) | set(extra_markers)) if m and m in rl]


# ── entrants + per-query records ────────────────────────────────────────────────
@dataclass
class Entrant:
    """One competitor in the head-to-head, with its (blinded-at-judge-time) report.

    `cost_usd` and `latency_s` are operator-supplied metadata recorded on the
    scorecard for the cost/wall-clock columns; they do NOT feed the categorical
    verdict (the judge scores text only). `corpus` is the evidence the report had
    access to (note dicts); the keyless RubricJudge uses it for grounding overlap.
    A pasted competitor report typically has no machine-readable corpus, so it
    defaults to empty — which the RubricJudge scores honestly (source_quality=fail
    with no corpus). See HEAD_TO_HEAD.md for how to supply a competitor corpus."""

    name: str
    report: str
    corpus: list[dict[str, Any]] = field(default_factory=list)
    cost_usd: float = 0.0
    latency_s: float = 0.0

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> Entrant:
        return cls(
            name=str(data["name"]),
            report=str(data.get("report", "")),
            corpus=list(data.get("corpus", [])),
            cost_usd=float(data.get("cost_usd", 0.0) or 0.0),
            latency_s=float(data.get("latency_s", 0.0) or 0.0),
        )


@dataclass
class EntrantScore:
    """An entrant's blinded verdict on one query, plus its cost/latency metadata."""

    name: str
    verdict: JudgeVerdict
    cost_usd: float
    latency_s: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "verdict": self.verdict.to_dict(),
            "cost_usd": round(self.cost_usd, 6),
            "latency_s": round(self.latency_s, 3),
        }


# Tally outcomes from bad-research's POINT OF VIEW: a "win" means a bad-research
# entrant beat the competitor on pass-rate for that query.
WIN = "win"
TIE = "tie"
LOSS = "loss"


@dataclass
class QueryResult:
    """One shared query scored across all entrants, with the bad-vs-competitor
    outcome decided on pass-rate (ties broken to TIE, never silently to a win)."""

    id: str
    query: str
    scores: list[EntrantScore]
    outcome: str  # WIN | TIE | LOSS, from bad-research's POV
    bad_name: str
    competitor_name: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "query": self.query,
            "outcome": self.outcome,
            "bad_entrant": self.bad_name,
            "competitor_entrant": self.competitor_name,
            "scores": [s.to_dict() for s in self.scores],
        }


def _outcome(bad_rate: float, comp_rate: float) -> str:
    """bad-research's outcome vs the competitor on a single query, by pass-rate.
    Equal pass-rates are an honest TIE — never rounded into a win."""
    if bad_rate > comp_rate:
        return WIN
    if bad_rate < comp_rate:
        return LOSS
    return TIE


# ── the scorecard ────────────────────────────────────────────────────────────────
@dataclass
class Scorecard:
    """The full head-to-head result: per-query outcomes + the aggregate W/T/L tally
    and per-axis breakdown. Emits JSON and a markdown table."""

    bad_name: str
    competitor_name: str
    results: list[QueryResult]
    llm_judged: bool = False
    blinded: bool = True

    @property
    def tally(self) -> dict[str, int]:
        """Aggregate W/T/L from bad-research's POV over every scored query."""
        t = {WIN: 0, TIE: 0, LOSS: 0}
        for r in self.results:
            t[r.outcome] += 1
        return t

    def verdict_line(self) -> str:
        """A one-line, honest summary of the tally. Never claims a win the math
        does not support; a wins<=losses tally reads as 'no win shown'."""
        t = self.tally
        n = len(self.results)
        if t[WIN] > t[LOSS]:
            head = f"bad-research leads {t[WIN]}-{t[LOSS]}-{t[TIE]} (W-L-T)"
        elif t[WIN] < t[LOSS]:
            head = f"competitor leads {t[LOSS]}-{t[WIN]}-{t[TIE]} (W-L-T for competitor)"
        else:
            head = f"tied {t[WIN]}-{t[LOSS]}-{t[TIE]} (W-L-T)"
        judge = "host-model LLMJudge" if self.llm_judged else "keyless deterministic RubricJudge"
        return f"{head} over {n} queries, scored by the {judge}."

    def _axis_breakdown(self) -> dict[str, dict[str, float]]:
        """Mean per-axis rail-credit for each entrant across all queries (a 0.0-1.0
        reporting number derived from the categorical rails — NOT a judge score).
        Lets the markdown surface which axes drive the tally."""
        out: dict[str, dict[str, float]] = {}
        for entrant in (self.bad_name, self.competitor_name):
            per_axis: dict[str, list[float]] = {a: [] for a in JUDGE_AXES}
            for r in self.results:
                for s in r.scores:
                    if s.name != entrant:
                        continue
                    rails = s.verdict.rails.as_str_dict()
                    for a in JUDGE_AXES:
                        per_axis[a].append(RAIL_CREDIT.get(rails.get(a, "fail"), 0.0))
            out[entrant] = {
                a: round(sum(v) / len(v), 6) if v else 0.0 for a, v in per_axis.items()
            }
        return out

    def to_dict(self) -> dict[str, Any]:
        return {
            "benchmark": "head-to-head",
            "disclaimer": (
                "Competitor reports are pasted by a human, not produced by this tool. "
                "Reports are BLINDED (tool markers stripped) before judging. Scoring "
                "reuses calibrate.judge: the keyless deterministic RubricJudge "
                "(grounding-overlap + citation-presence proxy, NOT semantic entailment) "
                "unless run with --llm (host-model LLMJudge). cost_usd/latency_s are "
                "operator-supplied metadata and do not feed the categorical verdict. "
                "This is the measurement apparatus; the tally below is whatever the "
                "real runs produced, not a claimed result."
            ),
            "bad_entrant": self.bad_name,
            "competitor_entrant": self.competitor_name,
            "blinded": self.blinded,
            "llm_judged": self.llm_judged,
            "tally": self.tally,
            "verdict": self.verdict_line(),
            "axis_breakdown": self._axis_breakdown(),
            "queries": [r.to_dict() for r in self.results],
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)

    def to_markdown(self) -> str:
        t = self.tally
        axis = self._axis_breakdown()
        lines: list[str] = [
            "# Head-to-Head Scorecard",
            "",
            f"**bad-research entrant:** `{self.bad_name}`  ",
            f"**competitor entrant:** `{self.competitor_name}`  ",
            f"**judge:** {'host-model LLMJudge' if self.llm_judged else 'keyless deterministic RubricJudge'}  ",
            f"**blinded:** {'yes' if self.blinded else 'no'}",
            "",
            "> Competitor reports are pasted by a human. Reports are blinded before judging.",
            "> The keyless judge is a grounding-overlap + citation-presence proxy, not",
            "> semantic entailment (see `docs/benchmarks/HEAD_TO_HEAD.md`). This is the",
            "> apparatus; the tally is whatever the real runs produced.",
            "",
            "## Aggregate (bad-research POV)",
            "",
            f"- **{self.verdict_line()}**",
            f"- Wins: **{t[WIN]}**  Ties: **{t[TIE]}**  Losses: **{t[LOSS]}**  "
            f"(of {len(self.results)} queries)",
            "",
            "### Per-axis mean rail-credit (0.0-1.0; derived from categorical rails)",
            "",
            "| axis | " + f"{self.bad_name} | {self.competitor_name} |",
            "|---|---|---|",
        ]
        for a in JUDGE_AXES:
            lines.append(
                f"| {a} | {axis[self.bad_name][a]:.3f} | {axis[self.competitor_name][a]:.3f} |"
            )
        lines += [
            "",
            "## Per-query",
            "",
            "| query | outcome | "
            + f"{self.bad_name} pass-rate | {self.competitor_name} pass-rate | "
            + f"{self.bad_name} $ | {self.competitor_name} $ | "
            + f"{self.bad_name} s | {self.competitor_name} s |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for r in self.results:
            by_name = {s.name: s for s in r.scores}
            b = by_name.get(self.bad_name)
            c = by_name.get(self.competitor_name)
            b_rate = f"{b.verdict.pass_rate:.3f}" if b else "-"
            c_rate = f"{c.verdict.pass_rate:.3f}" if c else "-"
            b_cost = f"{b.cost_usd:.4f}" if b else "-"
            c_cost = f"{c.cost_usd:.4f}" if c else "-"
            b_lat = f"{b.latency_s:.1f}" if b else "-"
            c_lat = f"{c.latency_s:.1f}" if c else "-"
            lines.append(
                f"| {r.id} | {r.outcome} | {b_rate} | {c_rate} | "
                f"{b_cost} | {c_cost} | {b_lat} | {c_lat} |"
            )
        return "\n".join(lines) + "\n"


# ── the run ────────────────────────────────────────────────────────────────────
def load_query_set(path: Path | str) -> list[dict[str, str]]:
    """Load a shared query set: JSON list of `{id, query, [modality]}`. Raises a
    clear ValueError on a malformed set (never a raw traceback)."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("query set must be a JSON list of {id, query} objects")
    out: list[dict[str, str]] = []
    for i, item in enumerate(data):
        if not isinstance(item, dict) or "id" not in item or "query" not in item:
            raise ValueError(f"query-set item {i} must have 'id' and 'query'")
        out.append({"id": str(item["id"]), "query": str(item["query"])})
    return out


def score_query(
    query: str,
    entrants: list[Entrant],
    *,
    judge: Judge,
    bad_name: str,
    competitor_name: str,
    blind: bool = True,
) -> list[EntrantScore]:
    """Blind (if asked) and judge every entrant's report for one query. The judge
    sees the blinded text only; cost/latency ride along as metadata."""
    scores: list[EntrantScore] = []
    for e in entrants:
        report = blind_report(e.report) if blind else e.report
        verdict = judge.judge(query, report, e.corpus)
        scores.append(
            EntrantScore(
                name=e.name, verdict=verdict, cost_usd=e.cost_usd, latency_s=e.latency_s
            )
        )
    return scores


def run_head_to_head(
    query_set: list[dict[str, str]],
    entrants_by_qid: dict[str, list[Entrant]],
    *,
    bad_name: str,
    competitor_name: str,
    judge: Judge | None = None,
    blind: bool = True,
) -> Scorecard:
    """Score a whole shared query set head-to-head and tally W/T/L.

    `entrants_by_qid` maps each query id to its list of entrants (must contain one
    named `bad_name` and one named `competitor_name`). Queries with a missing
    entrant are scored on whoever is present but contribute a TIE to the tally
    (never a silent win). Default judge: the keyless deterministic RubricJudge."""
    j = judge if judge is not None else RubricJudge()
    results: list[QueryResult] = []
    for item in query_set:
        qid, query = item["id"], item["query"]
        entrants = entrants_by_qid.get(qid, [])
        scores = score_query(
            query,
            entrants,
            judge=j,
            bad_name=bad_name,
            competitor_name=competitor_name,
            blind=blind,
        )
        by_name = {s.name: s for s in scores}
        bad = by_name.get(bad_name)
        comp = by_name.get(competitor_name)
        if bad is not None and comp is not None:
            outcome = _outcome(bad.verdict.pass_rate, comp.verdict.pass_rate)
        else:
            # Can't compare without both sides — honestly a non-result (TIE),
            # never scored as a bad-research win.
            outcome = TIE
        results.append(
            QueryResult(
                id=qid,
                query=query,
                scores=scores,
                outcome=outcome,
                bad_name=bad_name,
                competitor_name=competitor_name,
            )
        )
    return Scorecard(
        bad_name=bad_name,
        competitor_name=competitor_name,
        results=results,
        llm_judged=judge is not None and not isinstance(j, RubricJudge),
        blinded=blind,
    )


# ── keyless host-judge flow: emit tasks → host judges → ingest verdicts ──────────
# The orchestrating Claude IS the judge — no API key, no provider. `emit_judge_tasks`
# writes one BLINDED task file per entrant (rubric + blinded report + corpus + a
# write-`<id>.verdict.json` instruction) plus a manifest; the host reads each task
# and hand-writes the 5 categorical rails; `load_verdicts` ingests those rails
# through the EXISTING AxisRails.from_raw → JudgeVerdict.from_rails path and produces
# the SAME scorecard as the --llm/RubricJudge routes (a `HostJudge` keyed on the
# blinded report text is the Judge the harness runs).
JUDGE_MANIFEST_NAME = "manifest.json"


def _opaque_id(qid: str, index: int) -> str:
    """An entrant's opaque task id. Deliberately carries NO entrant identity —
    'entrant-01', not 'bad-research' — so the host judge cannot tell which entrant
    (bad-research vs competitor) it is grading. The manifest maps it back."""
    return f"{qid}__entrant-{index + 1:02d}"


def build_judge_task(query: str, blinded_report: str, corpus: list[dict[str, Any]], task_id: str) -> str:
    """The full task text the host judge reads for ONE blinded entrant report.
    The rubric (`JUDGE_SYSTEM`) is itself run through `blind_report` defensively;
    the report is supplied ALREADY blinded by the caller (blinding happens before
    the task is written, so the host never sees a tool name). Ends with an explicit
    instruction to write the 5 rails + rationale to `<task_id>.verdict.json`."""
    blinded_rubric = blind_report(JUDGE_SYSTEM)
    user_block = build_judge_user_prompt(query, blinded_report, corpus)
    verdict_schema = (
        "{\n"
        '  "factual": "pass|borderline|fail",\n'
        '  "citation": "pass|borderline|fail",\n'
        '  "completeness": "pass|borderline|fail",\n'
        '  "source_quality": "pass|borderline|fail",\n'
        '  "efficiency": "pass|borderline|fail",\n'
        '  "rationale": "<=2 sentences"\n'
        "}"
    )
    return (
        f"# Host judge task: {task_id}\n\n"
        "You are the HOST JUDGE for a blinded head-to-head. There is NO API key and "
        "NO model call — YOU read this file and grade it yourself. This report has "
        "been blinded (tool-identifying markers stripped) so you cannot tell which "
        "tool produced it; grade the TEXT only, on its merits.\n\n"
        "## Rubric (how to grade)\n\n"
        f"{blinded_rubric}\n\n"
        "## What to grade\n\n"
        f"{user_block}\n\n"
        "## Your instruction\n\n"
        f"Read the rubric and the report above, then write the 5 categorical rails "
        f"(factual / citation / completeness / source_quality / efficiency, each one "
        f"of pass / borderline / fail) plus a short rationale to a file named "
        f"`{task_id}.verdict.json` in this directory, as a single JSON object of "
        f"exactly this shape:\n\n"
        f"```json\n{verdict_schema}\n```\n\n"
        "No numbers, no prose outside the JSON. One rail per axis.\n"
    )


def emit_judge_tasks(
    query_set: list[dict[str, str]],
    entrants_by_qid: dict[str, list[Entrant]],
    out_dir: Path,
    *,
    bad_name: str,
    competitor_name: str,
    blind: bool = True,
) -> dict[str, Any]:
    """Write one BLINDED `<task_id>.task.md` per entrant + a `manifest.json` mapping
    each task back to its query and entrant, so `load_verdicts` can reassemble.

    Blinding happens HERE, before the task is written — the persisted task file and
    the manifest's recorded report are the blinded text, so nothing the host reads
    (and nothing it ingests against) carries a tool name. Returns the manifest dict
    that was written (handy for callers/tests)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    by_qid = {q["id"]: q["query"] for q in query_set}
    tasks: list[dict[str, Any]] = []
    for qid, ents in entrants_by_qid.items():
        query = by_qid.get(qid, "")
        for i, e in enumerate(ents):
            blinded = blind_report(e.report) if blind else e.report
            task_id = _opaque_id(qid, i)
            task_text = build_judge_task(query, blinded, e.corpus, task_id)
            (out_dir / f"{task_id}.task.md").write_text(task_text, encoding="utf-8")
            tasks.append(
                {
                    "task_id": task_id,
                    "query_id": qid,
                    "query": query,
                    "entrant_name": e.name,
                    "report": blinded,  # the EXACT (blinded) text load_verdicts judges against
                    "corpus": e.corpus,
                    "cost_usd": e.cost_usd,
                    "latency_s": e.latency_s,
                    "verdict_file": f"{task_id}.verdict.json",
                }
            )
    manifest = {
        "benchmark": "head-to-head-judge-tasks",
        "bad_name": bad_name,
        "competitor_name": competitor_name,
        "blinded": blind,
        "tasks": tasks,
    }
    (out_dir / JUDGE_MANIFEST_NAME).write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def _verdict_from_rails_file(path: Path) -> JudgeVerdict:
    """Ingest ONE host-written `*.verdict.json` rails file through the EXISTING
    AxisRails.from_raw → JudgeVerdict.from_rails path (same coercion the --llm route
    uses: missing/garbage rails degrade to FAIL, never a crash)."""
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"verdict file {path} must be a JSON object of axis rails")
    rails = AxisRails.from_raw(raw)
    return JudgeVerdict.from_rails(rails, rationale=str(raw.get("rationale", "")))


def load_verdicts(
    verdicts_dir: Path,
) -> tuple[list[dict[str, str]], dict[str, list[Entrant]], HostJudge, str, str, bool]:
    """Read the manifest + the host-written `*.verdict.json` files and reassemble
    everything `run_head_to_head` needs for the keyless semantic scorecard.

    Returns (query_set, entrants_by_qid, host_judge, bad_name, competitor_name,
    blinded). The `HostJudge` is POSITIONAL: its verdict list is built in the same
    (query order → entrant order) the harness will call `judge()` in, so each
    entrant gets its own host verdict even when two reports blind to identical text
    (a text key would collide there). A task whose verdict file is missing leaves a
    `None` at that position → the HostJudge degrades it to all-FAIL (never a crash,
    never a silent pass). NOTE: callers must run the harness with `blind=False`
    here — the manifest's reports are already blinded; re-blinding is a no-op but
    the positional contract does not depend on the report text at all."""
    man_path = verdicts_dir / JUDGE_MANIFEST_NAME
    if not man_path.exists():
        raise FileNotFoundError(
            f"judge manifest not found: {man_path} "
            "(did you run --emit-judge-tasks into this dir first?)"
        )
    manifest = json.loads(man_path.read_text(encoding="utf-8"))
    tasks = manifest.get("tasks", [])
    if not isinstance(tasks, list) or not tasks:
        raise ValueError(f"manifest {man_path} has no 'tasks' to ingest")

    query_set: list[dict[str, str]] = []
    seen_qids: set[str] = set()
    entrants_by_qid: dict[str, list[Entrant]] = {}
    verdicts: list[JudgeVerdict | None] = []

    for t in tasks:
        qid = str(t["query_id"])
        if qid not in seen_qids:
            seen_qids.add(qid)
            query_set.append({"id": qid, "query": str(t.get("query", ""))})
        report = str(t.get("report", ""))
        entrants_by_qid.setdefault(qid, []).append(
            Entrant(
                name=str(t["entrant_name"]),
                report=report,
                corpus=list(t.get("corpus", [])),
                cost_usd=float(t.get("cost_usd", 0.0) or 0.0),
                latency_s=float(t.get("latency_s", 0.0) or 0.0),
            )
        )
        vfile = verdicts_dir / str(t.get("verdict_file", f"{t['task_id']}.verdict.json"))
        verdicts.append(_verdict_from_rails_file(vfile) if vfile.exists() else None)

    host = HostJudge(verdicts=verdicts)
    return (
        query_set,
        entrants_by_qid,
        host,
        str(manifest.get("bad_name") or "bad-research"),
        str(manifest.get("competitor_name") or "competitor"),
        bool(manifest.get("blinded", True)),
    )


__all__ = [
    "JUDGE_MANIFEST_NAME",
    "LOSS",
    "TIE",
    "TOOL_MARKERS",
    "WIN",
    "Entrant",
    "EntrantScore",
    "QueryResult",
    "Scorecard",
    "blind_report",
    "build_judge_task",
    "emit_judge_tasks",
    "load_query_set",
    "load_verdicts",
    "markers_present",
    "run_head_to_head",
    "score_query",
]
